version: 2.1

executors:
  node14-executor:
    docker:
      - image: circleci/node:14.16.1

jobs:
  release:
    executor: node14-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release

workflows:
  version: 2
  build:
    jobs:
      - release:
          context: docker
          filters:
            branches:
              only:
                - master